kind: pipeline
name: default

trigger:
  event:
    - push
    - pull_request
    - tag

steps:
  - name: install
    image: node:alpine
    commands:
      - yarn install

  - name: build
    image: node:alpine
    commands:
      - yarn build
    depends_on:
      - install

  - name: node-12
    image: node:12-alpine
    commands:
      - yarn test:unit
    depends_on:
      - build

  - name: node-14
    image: node:14-alpine
    commands:
      - yarn test:unit
    depends_on:
      - build

  - name: coverage-build
    image: node:alpine
    commands:
      - yarn test:coverage
    depends_on:
      - node-12
      - node-14
      - browsers

  - name: coverage-report
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
    depends_on:
      - coverage-build
